"""Remove PostgreSQL-specific pinned comment index for database compatibility

Revision ID: 2a470d8ac280
Revises: 4339362128b0
Create Date: 2025-10-15 19:50:50.217843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a470d8ac280'
down_revision = '4339362128b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_pinned_comment_per_recipe'), postgresql_where='(is_pinned = true)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_pinned_comment_per_recipe'), ['recipe_id'], unique=True, postgresql_where='(is_pinned = true)')

    # ### end Alembic commands ###
