"""Add display_order to RecipeImage

Revision ID: 37126fff9b51
Revises: 9f41d83fe1fb
Create Date: 2025-09-10 07:55:10.822802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37126fff9b51'
down_revision = '9f41d83fe1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_image', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
