"""empty message

Revision ID: 65956cca3a5a
Revises: 6552780c8d59
Create Date: 2025-10-13 11:20:02.071560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65956cca3a5a'
down_revision = '6552780c8d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add a temporary column to store the converted data
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_temp', sa.JSON(), nullable=True))

    # Convert existing string data to JSON format
    # This maps country codes to their full names
    op.execute("""
        UPDATE users SET country_temp = 
        CASE 
            WHEN country IS NOT NULL AND country != '' THEN 
                json_build_object('code', country, 'name', 
                    CASE country
                        WHEN 'US' THEN 'United States'
                        WHEN 'CA' THEN 'Canada'
                        WHEN 'MX' THEN 'Mexico'
                        WHEN 'GB' THEN 'United Kingdom'
                        WHEN 'DE' THEN 'Germany'
                        WHEN 'FR' THEN 'France'
                        WHEN 'IT' THEN 'Italy'
                        WHEN 'ES' THEN 'Spain'
                        WHEN 'NL' THEN 'Netherlands'
                        WHEN 'BE' THEN 'Belgium'
                        WHEN 'CH' THEN 'Switzerland'
                        WHEN 'AT' THEN 'Austria'
                        WHEN 'SE' THEN 'Sweden'
                        WHEN 'NO' THEN 'Norway'
                        WHEN 'DK' THEN 'Denmark'
                        WHEN 'FI' THEN 'Finland'
                        WHEN 'PT' THEN 'Portugal'
                        WHEN 'IE' THEN 'Ireland'
                        WHEN 'GR' THEN 'Greece'
                        WHEN 'PL' THEN 'Poland'
                        WHEN 'CZ' THEN 'Czech Republic'
                        WHEN 'HU' THEN 'Hungary'
                        WHEN 'SK' THEN 'Slovakia'
                        WHEN 'SI' THEN 'Slovenia'
                        WHEN 'HR' THEN 'Croatia'
                        WHEN 'BA' THEN 'Bosnia and Herzegovina'
                        WHEN 'RS' THEN 'Serbia'
                        WHEN 'ME' THEN 'Montenegro'
                        WHEN 'MK' THEN 'North Macedonia'
                        WHEN 'AL' THEN 'Albania'
                        WHEN 'BG' THEN 'Bulgaria'
                        WHEN 'RO' THEN 'Romania'
                        WHEN 'MD' THEN 'Moldova'
                        WHEN 'UA' THEN 'Ukraine'
                        WHEN 'BY' THEN 'Belarus'
                        WHEN 'RU' THEN 'Russia'
                        WHEN 'EE' THEN 'Estonia'
                        WHEN 'LV' THEN 'Latvia'
                        WHEN 'LT' THEN 'Lithuania'
                        WHEN 'LU' THEN 'Luxembourg'
                        WHEN 'MT' THEN 'Malta'
                        WHEN 'CY' THEN 'Cyprus'
                        WHEN 'IS' THEN 'Iceland'
                        WHEN 'LI' THEN 'Liechtenstein'
                        WHEN 'MC' THEN 'Monaco'
                        WHEN 'SM' THEN 'San Marino'
                        WHEN 'VA' THEN 'Vatican City'
                        WHEN 'AU' THEN 'Australia'
                        WHEN 'NZ' THEN 'New Zealand'
                        WHEN 'JP' THEN 'Japan'
                        WHEN 'KR' THEN 'South Korea'
                        WHEN 'CN' THEN 'China'
                        WHEN 'IN' THEN 'India'
                        WHEN 'TH' THEN 'Thailand'
                        WHEN 'VN' THEN 'Vietnam'
                        WHEN 'MY' THEN 'Malaysia'
                        WHEN 'SG' THEN 'Singapore'
                        WHEN 'ID' THEN 'Indonesia'
                        WHEN 'PH' THEN 'Philippines'
                        WHEN 'ZA' THEN 'South Africa'
                        WHEN 'EG' THEN 'Egypt'
                        WHEN 'BR' THEN 'Brazil'
                        WHEN 'AR' THEN 'Argentina'
                        WHEN 'CL' THEN 'Chile'
                        WHEN 'CO' THEN 'Colombia'
                        WHEN 'PE' THEN 'Peru'
                        WHEN 'VE' THEN 'Venezuela'
                        WHEN 'UY' THEN 'Uruguay'
                        WHEN 'PY' THEN 'Paraguay'
                        WHEN 'BO' THEN 'Bolivia'
                        WHEN 'EC' THEN 'Ecuador'
                        WHEN 'GY' THEN 'Guyana'
                        WHEN 'SR' THEN 'Suriname'
                        WHEN 'GT' THEN 'Guatemala'
                        WHEN 'BZ' THEN 'Belize'
                        WHEN 'SV' THEN 'El Salvador'
                        WHEN 'HN' THEN 'Honduras'
                        WHEN 'NI' THEN 'Nicaragua'
                        WHEN 'CR' THEN 'Costa Rica'
                        WHEN 'PA' THEN 'Panama'
                        WHEN 'JM' THEN 'Jamaica'
                        WHEN 'HT' THEN 'Haiti'
                        WHEN 'DO' THEN 'Dominican Republic'
                        WHEN 'CU' THEN 'Cuba'
                        WHEN 'TT' THEN 'Trinidad and Tobago'
                        WHEN 'BB' THEN 'Barbados'
                        WHEN 'GD' THEN 'Grenada'
                        WHEN 'VC' THEN 'Saint Vincent and the Grenadines'
                        WHEN 'LC' THEN 'Saint Lucia'
                        WHEN 'KN' THEN 'Saint Kitts and Nevis'
                        WHEN 'DM' THEN 'Dominica'
                        WHEN 'AG' THEN 'Antigua and Barbuda'
                        WHEN 'BS' THEN 'Bahamas'
                        ELSE country  -- fallback to just the code if not found
                    END
                )
            ELSE NULL
        END
    """)

    # Drop the old column and rename the temp column
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.alter_column('country_temp', new_column_name='country')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert JSON data back to string format (extract the code)
    op.execute("""
        ALTER TABLE users ADD COLUMN country_temp VARCHAR(100);
        UPDATE users SET country_temp = 
        CASE 
            WHEN country IS NOT NULL THEN country->>'code'
            ELSE NULL
        END;
    """)
    
    # Drop the JSON column and rename the temp column back
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.alter_column('country_temp', new_column_name='country', type_=sa.VARCHAR(length=100), existing_nullable=True)
