"""empty message

Revision ID: 6e29b7f42ee0
Revises: 37126fff9b51
Create Date: 2025-09-26 11:56:40.749200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e29b7f42ee0'
down_revision = '37126fff9b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plain_psswrd', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plain_psswrd')

    # ### end Alembic commands ###
