"""empty message

Revision ID: 7f993a6dc933
Revises: 74404878a1a9
Create Date: 2025-10-07 17:26:18.967883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f993a6dc933'
down_revision = '74404878a1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('unique_pinned_comment_per_recipe', ['recipe_id'], unique=True, postgresql_where=sa.text('is_pinned = true'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('unique_pinned_comment_per_recipe', postgresql_where=sa.text('is_pinned = true'))

    # ### end Alembic commands ###
