"""empty message

Revision ID: 933647cc0d57
Revises: 0763d677d453
Create Date: 2025-09-01 08:06:11.921326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933647cc0d57'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.CheckConstraint('char_length(title)              > 0', name='check_title_not_empty'),
    sa.CheckConstraint('json_array_length(ingredients)  > 0', name='check_has_ingredients'),
    sa.CheckConstraint('json_array_length(instructions) > 0', name='check_has_instructions'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('hashed_psswrd', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('profile_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('profile_url')
        batch_op.drop_column('hashed_psswrd')
        batch_op.drop_column('full_name')
        batch_op.drop_column('username')

    op.drop_table('recipe')
    # ### end Alembic commands ###
