"""empty message

Revision ID: b0c00739e473
Revises: 28c7661c61f6
Create Date: 2025-09-29 19:31:16.635838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c00739e473'
down_revision = '28c7661c61f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('last_message_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
